#!/bin/bash/env Rscript
if(!require(MachineShop)) install.packages("MachineShop",repos = "https://cloud.r-project.org")
if(!require(readr)) install.packages("readr",repos = "https://cloud.r-project.org")
if(!require(doSNOW)) install.packages("doSNOW",repos = "https://cloud.r-project.org")
if(!require(dplyr)) install.packages("dplyr",repos = "https://cloud.r-project.org")
if(!require(praznik)) install.packages("praznik",repos = "https://cloud.r-project.org")
if(!require(tree)) install.packages("tree",repos = "https://cloud.r-project.org")
if(!require(randomForest)) install.packages("randomForest",repos = "https://cloud.r-project.org")
if(!require(e1071)) install.packages("e1071",repos = "https://cloud.r-project.org")
if(!require(xgboost)) install.packages("xgboost",repos = "https://cloud.r-project.org")
